version: '3'

services:
  redis:
    image: docker.io/bitnami/redis:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

  influxdb:
    image: influxdb:1.8-alpine
    environment:
      - INFLUXDB_ADMIN_ENABLED=false
      - INFLUXDB_DB=prometheus
      - INFLUXDB_HTTP_LOG_ENABLED=false
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_USER=influxdb
      - INFLUXDB_USER_PASSWORD=influxdb
    ports:
      - '8086:8086'

volumes:
  redis_data:
    driver: local
